### ISSUE TITLE
Patches automagic expects newline after SourceX: lines

### ISSUE THREAD

**Issue by yac** [redhat-openstack/rdopkg#1]
`SpecFileParseError: Error parsing .spec file 'openstack-sahara.spec': Failed to append PatchXXXX: lines`

Either fix this or document this requiremnt in the resulting error message.

**Comment by apevec** [comment]
Confirmed, I've just hit this in keystonemiddleware, workaround:

 Source0:        https://pypi.python.org/packages/source/k/%{pypi_name}/%{pypi_name}-%{version}.tar.gz
+
 BuildArch:      noarch

**Comment by yac** [comment]
Other bugs related to PatchXXXX parsing: #15, #18

**Comment by yac** [comment]
Other bugs related to PatchXXXX parsing: #15, #18

**Comment by ktdreyer** [comment]
I hit this again today, in a package that had the following:

```
...
Source31: cool-library-1.0.tar.gz
Provides: bundled(cool-library) = 1.0

```

Swapping the ordering of the lines so that `Source31:` was the final line before the newline allowed rdopkg to parse the .spec file correctly.
