### ISSUE TITLE
handle version tags with "v" prefix

### ISSUE THREAD

**Issue by ktdreyer** [redhat-openstack/rdopkg#14]
In Ceph and its utilities we use version tags of the form "`v0.94.1`", "`v0.94.2`", etc.

Unfortunately for us, rdopkg assumes that an upstream tag is simply a bare number, with no "`v`" prefix.

Can rdopkg handle this case?

**Comment by hguemar** [comment]
It could be used in more projects if we fix that in patches mgmt related commands :+1:

**Comment by yac** [comment]
Some commands that only require git ref will work fine, but `new-version` assumes git tag == version. 

As @hguemar said, it would be nice to support vX.Y.Z and it should be doable without much suffering.

**Comment by yac** [comment]
5b3400a0ea3b97bbdf16 adds support for vX.Y.Z tags, but it needs thorough testing.

Also note that `rdopkg pkgenv` distplays detected tag style (X.Y.Z or vX.Y.Z)
