### ISSUE TITLE
rdopkg can't parse .spec with comments in between PatchXXXX: lines

### ISSUE THREAD

**Issue by ktdreyer** [redhat-openstack/rdopkg#18]
If I put a comment in between my PatchXXXX lines, rdopkg will fail to parse the .spec file when I run `rdopkg patch`.

For example, my .spec file contains something like:

```
...
Patch0011: 0011-my-eleventh-change.patch
# This is a comment about patch 12, my favorite patch.
Patch0012: 0012-my-twelfth-change.patch
...
```

and `rdopkg patch` fails with a `SpecFileParseError`

**Comment by yac** [comment]
I agree it'd nice to handle this in order to make converting to rdopkg-managed distgit easily.

However, I wonder how to handle this. Find first and last PatchXXXX and delete everything in between? That's rather intrusive... Any thoughts?

**Comment by ktdreyer** [comment]
I think that's actually ok to delete everything in between the first and last PatchXXXX for now. It is less-confusing than crashing, because the crash takes a while to figure out "what caused the parse error?". At least when we delete all lines, it's easy to see with `git show`.

**Comment by Akasurde** [comment]
@yac I would like to help in this. Let me know how can I help.
