### ISSUE TITLE
rdopkg can't parse .spec no blank lines between Source0 and PatchXXXX

### ISSUE THREAD

**Issue by ktdreyer** [redhat-openstack/rdopkg#20]
@trhoden noticed that `rdopkg` can't parse the .spec file when there's no blank lines between Source0 and Patch0:

```
Source0: ceph-deploy-1.5.25.tar.gz
Patch1: 0001-my-awesome-changes.patch
```

I guess we have to add the newline by hand?

**Comment by apevec** [comment]
Duplicate of https://github.com/redhat-openstack/rdopkg/issues/1
