### ISSUE TITLE
rdopkg rpm requires vim, but not installed

### ISSUE THREAD

**Issue by bdemers** [redhat-openstack/rdopkg#24]
`rdopkg update` uses `vim` but was not installed as a dependency

```
$ rdopkg --version
0.29.1 (rdoupdate 0.14)
```

NOTE: $EDITOR is unset

Obviously it is an easy work around, but the error message isn't clear, as it looks like my `up.yml` file was missing (generic `OSError: [Errno 2] No such file or directory` error)

**Comment by pixelb** [comment]
The error should be improved, though I'd argue that $EDITOR being unset is unusual and dependencies are best avoided if possible.

**Comment by bdemers** [comment]
I'm not sure i'd say it was rare, but defaulting to `vi` rather then `vim` might be an easy way out.

https://github.com/redhat-openstack/rdopkg/blob/master/rdopkg/helpers.py#L33

**Comment by yac** [comment]
I covered the special case of missing command in the run helper and also made the message clear for editor invocation:

    Failed to find suitable text editor. Please set $EDITOR environment variable.

Fixed in 1353ea7272559f59f6e387cd62b4269fa1deea11

**Comment by bdemers** [comment]
Cool!
