### ISSUE TITLE
rdopkg reqcheck is not using stdout

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/rdopkg#25]
rdopkg-0.29.1-1.fc21.noarch
$ rdopkg reqcheck > 00reqs
  python-oslo-concurrency >=2.3.0  (>=2.3.0 in .spec)
... (snip rest of stderr output which should be going to stdout) ...
$ cat 00reqs
```
## get_package_env
## reqcheck

MET:

VERSION NOT ENFORCED:

VERSION MISMATCH:

MISSING:
```

**Comment by yac** [comment]
Fixed in bbd6b7e9627c63ba29189ded7b135a647695ffe5.
