### ISSUE TITLE
rdopkg new-version should work without patches branches

### ISSUE THREAD

**Issue by hguemar** [redhat-openstack/rdopkg#29]
rdopkg new-version requires that the patch branch exists, even when there's no patch.
1. need a switch to disable that when there are no patches
2. preferably, if there are patches, print a warning message to tell user that they should create it

We could also automate patches branches creation but much lower priority.

**Comment by apevec** [comment]
As a workaround, you can run rdopkg new-version --bump-only which doesn't require patches branch:
 -b, --bump-only       only bump .spec to new version a la rpmdev-bumpspec

**Comment by yac** [comment]
Yes, `-b/--bump-only` should be automatic on missing patches branch. On it.

**Comment by yac** [comment]
Fixed in 85cb99907.
