### ISSUE TITLE
new-version regression

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/rdopkg#34]
Since
https://github.com/redhat-openstack/rdopkg/commit/85cb999070c15a3905d0c1ae290e6e912540c60b
patches branch is effectively ignored, I have:
patches	git://github.com/redhat-openstack/keystone.git
with f23-patches rebased on top of 2015.1.2

$ rdopkg new-version 2015.1.2
## new_version_setup
Patches branch patches/f23-patches not found. Running in --bump-only mode.
## update_spec
...

**Comment by yac** [comment]
This is fixed in latest, right?

**Comment by yac** [comment]
Reopen if you encounter this, should be fixed.
