### ISSUE TITLE
Instead of only looking at patches-base line in the spec file, allow for filtering out patches by regex

### ISSUE THREAD

**Issue by djipko** [redhat-openstack/rdopkg#37]
Problem we are trying to solve:
---

Because our CI configuration is part of the branch we use to generate patches with the help of rdopkg update-patches action, our current workflow for modifying it is as follows:

1) Propose a change that affects the CI config in gerrit
2) Wait for CI, see if results are satisfactory and merge the change

Instead of being done, we now have to *also* do the following set of tasks that make us sad:

3) rebase the branch that the patch just merged on so as to move the CI config patch to the "bottom" so that it will not be caught and added to dist-git on the next run of rdopkg update-patches
4) Update the spec file in dist-git by just changing the patches_base comment line (sometimes this is not possible at all for reasons I won't get into here. In this case we are **very** sad).
5) Push the dist-git change
6) Force push the branch we just rebased to gerrit. Since CI config does not get worked on a lot in parallel this does not really break people, but it is very brittle and, honestly, annoying.

What we propose to do:
---

Add a --filter-out (or similar) switch to the update-patches action which would allow for an arbitrary regex to be passed, this regex would filter out any patches that would otherwise end up in the dist-git repo, and have commit messages that match the regex (or at least title lines). So we could do something like:

`$rdopkg update-patches --filter-out "^CI-CONFIG.*" ` which would generate patches from a) commits above patches_base so that we are backwards compatible b) that have commit messages that **do no*t* start with "CI-CONFIG"

If the maintainers of rdopkg are on board with this idea - I'd be happy to hack up a patch to do this.

**Comment by apevec** [comment]
Copying comment from proposed patch:
:+1: for # filter_out "magic" comment
:-1: for adding --filter-out new CLI option

Too expand, this should be more reliable, developers would be forgetting to use CLI option.

**Comment by apevec** [comment]
"Add patches_ignore magic comment" was merged.
