### ISSUE TITLE
Online documentation link broken

### ISSUE THREAD

**Issue by gbraad** [redhat-openstack/rdopkg#39]
The link [1] in the README to the online documentation is broken. This link is also mentioned in the RDO packaging guide [2].

[1] https://www.rdoproject.org/packaging/rdopkg/rdopkg.1.html
[2] https://www.rdoproject.org/packaging/index.html

**Comment by apevec** [comment]
rdopkg man page publishing was not migrated to the new website, I've reported it in 
https://github.com/redhat-openstack/website/issues/237
@yac ^please have a look!
