### ISSUE TITLE
Support git-ish `rdopkg CMD --continue`

### ISSUE THREAD

**Issue by yac** [redhat-openstack/rdopkg#4]
Although I find `rdopkg --continue` to be more conveinent, let's support `rdopkg command --continue` to be consistent with git.

**Comment by apevec** [comment]
Bonus points for checking if CMD is the command recorded in .rdopkg.json

**Comment by yac** [comment]
Should be supported by global --continue and --abort in 191b53e2d3ac85c84a0.
