### ISSUE TITLE
Similar project rebase-helper

### ISSUE THREAD

**Issue by phracek** [redhat-openstack/rdopkg#45]
Hi folks,

we have similar project in Fedora called rebase-helper.
https://github.com/phracek/rebase-helper

If you have any questions do not hesitate to contact me phracek@redhat.com

Greetings
Petr

**Comment by yac** [comment]
Hey, thanks for the info!

It seems like `rebase-helper` is a single-purpose tool, while `rdopkg` strives to serve as a convenient collection of glue needed to get our packaging job done, not limited to rebases. 

More importantly `rebase-helper` seems pretty universal, it should work on any reasonable package while `rdopkg` enforces certain conventions regarding the dist-git and associated patches branches that give it extra automation options.
