### ISSUE TITLE
patches_ignore keyword not used by the new-version command

### ISSUE THREAD

**Issue by lyarwood** [redhat-openstack/rdopkg#54]
patches_ignore keyword not used by the new-version command, causing unwanted patches to be applied (or at least an attempt made to apply them) after a rebase.

**Comment by apevec** [comment]
Hmm, not sure why is that, new-version is using update-patches as a last step:
https://github.com/redhat-openstack/rdopkg/blob/master/rdopkg/actions.py#L89

@lyarwood can you show an example spec and repo where this was observed? Does rdopkg update-patches work?

**Comment by lyarwood** [comment]
@apevec Apologies, I was somehow using the 0.32.1 version of rdopkg so this isn't a bug at all, closing.
